import type { NumerologyMeaning, NumerologyNumber } from "./types.ts";

export const NUMEROLOGY_MEANINGS: Record<NumerologyNumber, NumerologyMeaning> = {
  1: {
    number: 1,
    title: "The Initiator",
    essence: "Independent energy that learns through courage, originality, and self-direction.",
    strengths: ["initiative", "independence", "decisiveness"],
    challenges: ["impatience", "isolation", "over-control"],
    careerThemes: ["leadership", "entrepreneurship", "independent ownership"],
    relationshipThemes: ["respect", "autonomy", "direct communication"],
    growthLesson: "Lead without carrying everything alone.",
  },
  2: {
    number: 2,
    title: "The Harmoniser",
    essence: "Sensitive, cooperative energy that notices nuance and creates connection.",
    strengths: ["diplomacy", "empathy", "patience"],
    challenges: ["indecision", "over-sensitivity", "people-pleasing"],
    careerThemes: ["partnership", "mediation", "supportive leadership"],
    relationshipThemes: ["emotional safety", "reciprocity", "gentle honesty"],
    growthLesson: "Protect your own voice while creating harmony.",
  },
  3: {
    number: 3,
    title: "The Communicator",
    essence: "Expressive energy that grows through creativity, language, and joyful connection.",
    strengths: ["communication", "imagination", "optimism"],
    challenges: ["scattered focus", "avoidance", "inconsistency"],
    careerThemes: ["writing", "media", "creative communication"],
    relationshipThemes: ["playfulness", "verbal affection", "shared inspiration"],
    growthLesson: "Give your creativity enough structure to become lasting work.",
  },
  4: {
    number: 4,
    title: "The Builder",
    essence: "Grounded energy that turns discipline, order, and patience into stability.",
    strengths: ["reliability", "planning", "persistence"],
    challenges: ["rigidity", "overwork", "fear of change"],
    careerThemes: ["systems", "operations", "long-term craftsmanship"],
    relationshipThemes: ["loyalty", "consistency", "practical care"],
    growthLesson: "Build strong foundations without making them a cage.",
  },
  5: {
    number: 5,
    title: "The Explorer",
    essence: "Adaptive energy that seeks freedom, variety, experience, and meaningful change.",
    strengths: ["versatility", "curiosity", "resilience"],
    challenges: ["restlessness", "impulsiveness", "unfinished commitments"],
    careerThemes: ["travel", "sales", "fast-changing environments"],
    relationshipThemes: ["space", "adventure", "honest expectations"],
    growthLesson: "Choose freedom with intention rather than through escape.",
  },
  6: {
    number: 6,
    title: "The Nurturer",
    essence: "Responsible, heart-led energy focused on care, beauty, home, and service.",
    strengths: ["compassion", "responsibility", "devotion"],
    challenges: ["over-giving", "perfectionism", "unwanted rescuing"],
    careerThemes: ["teaching", "healing service", "community stewardship"],
    relationshipThemes: ["commitment", "care", "shared responsibility"],
    growthLesson: "Care deeply without taking ownership of everyone else's path.",
  },
  7: {
    number: 7,
    title: "The Seeker",
    essence: "Reflective energy that looks beneath appearances for knowledge, truth, and meaning.",
    strengths: ["analysis", "intuition", "discernment"],
    challenges: ["withdrawal", "overthinking", "emotional distance"],
    careerThemes: ["research", "strategy", "specialist knowledge"],
    relationshipThemes: ["depth", "trust", "intellectual connection"],
    growthLesson: "Let insight become connection, not only private understanding.",
  },
  8: {
    number: 8,
    title: "The Achiever",
    essence: "Purposeful energy that learns through power, resources, responsibility, and results.",
    strengths: ["authority", "ambition", "resourcefulness"],
    challenges: ["work obsession", "control", "status pressure"],
    careerThemes: ["management", "finance", "large-scale execution"],
    relationshipThemes: ["mutual respect", "loyalty", "balanced power"],
    growthLesson: "Use influence ethically and let success include inner stability.",
  },
  9: {
    number: 9,
    title: "The Humanitarian",
    essence: "Compassionate energy that seeks meaning through service, completion, and wider perspective.",
    strengths: ["generosity", "wisdom", "inclusive vision"],
    challenges: ["over-idealism", "emotional burden", "difficulty letting go"],
    careerThemes: ["advocacy", "arts", "mission-led work"],
    relationshipThemes: ["compassion", "forgiveness", "healthy closure"],
    growthLesson: "Serve without losing your boundaries or carrying every sorrow.",
  },
  11: {
    number: 11,
    title: "The Intuitive Messenger",
    essence: "Heightened intuitive energy that translates inspiration into language, art, or guidance.",
    strengths: ["inspiration", "sensitivity", "vision"],
    challenges: ["nervous intensity", "self-doubt", "emotional overload"],
    careerThemes: ["creative leadership", "guidance", "visionary communication"],
    relationshipThemes: ["soulful connection", "sensitivity", "grounded honesty"],
    growthLesson: "Ground inspiration in ordinary routines and clear boundaries.",
  },
  22: {
    number: 22,
    title: "The Master Builder",
    essence: "Visionary yet practical energy capable of turning ambitious ideas into useful structures.",
    strengths: ["strategic vision", "execution", "endurance"],
    challenges: ["pressure", "over-responsibility", "fear of falling short"],
    careerThemes: ["institution building", "systems leadership", "large projects"],
    relationshipThemes: ["shared purpose", "reliability", "realistic expectations"],
    growthLesson: "Build at a human pace and share the weight of the vision.",
  },
  33: {
    number: 33,
    title: "The Compassionate Teacher",
    essence: "Service-oriented master energy that combines expression, care, and spiritual responsibility.",
    strengths: ["compassion", "teaching", "uplifting presence"],
    challenges: ["self-sacrifice", "impossible standards", "emotional exhaustion"],
    careerThemes: ["teaching", "healing leadership", "creative service"],
    relationshipThemes: ["devotion", "acceptance", "mutual care"],
    growthLesson: "Offer love and guidance without abandoning your own needs.",
  },
};

export function getNumerologyMeaning(number: NumerologyNumber) {
  return NUMEROLOGY_MEANINGS[number];
}
