"use client";
import { useEffect, useState } from "react";
import { useSettingsProfile } from "@/components/providers/SettingsProfileProvider";
import { supabase } from "@/lib/supabaseClient";

export default function ContactForm() {
  const { profile, loadProfile } = useSettingsProfile(); const [form, setForm] = useState({ name: "", email: "", subject: "", message: "" }); const [status, setStatus] = useState<"idle"|"loading"|"success">("idle"); const [error, setError] = useState("");
  useEffect(() => { void loadProfile(); }, [loadProfile]);
  useEffect(() => { if (profile) setForm((old) => ({ ...old, name: old.name || profile.fullName, email: old.email || profile.email })); }, [profile]);
  async function submit(e: React.FormEvent) { e.preventDefault(); setStatus("loading"); setError(""); try { const { data: { session } } = await supabase.auth.getSession(); const response = await fetch("/api/contact", { method: "POST", headers: { "Content-Type": "application/json", ...(session && { Authorization: `Bearer ${session.access_token}` }) }, body: JSON.stringify(form) }); const data = await response.json() as { message?: string }; if (!response.ok) throw new Error(data.message || "Your message could not be sent. Please try again."); setStatus("success"); setForm((old) => ({ ...old, subject: "", message: "" })); } catch (e) { setStatus("idle"); setError(e instanceof Error ? e.message : "Your message could not be sent. Please try again."); } }
  const cls = "mt-2 min-h-12 w-full rounded-xl border border-white/10 bg-[#020817]/70 px-3 text-white outline-none focus:border-sky-400/50";
  return <form onSubmit={submit} className="mt-9 space-y-5 rounded-3xl border border-white/10 bg-[#071225]/85 p-6 sm:p-8"><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm text-white/60">Name<input required maxLength={100} className={cls} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label className="text-sm text-white/60">Email<input required type="email" maxLength={254} className={cls} value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /></label></div><label className="block text-sm text-white/60">Subject<input required maxLength={160} className={cls} value={form.subject} onChange={(e) => setForm({ ...form, subject: e.target.value })} /></label><label className="block text-sm text-white/60">Message<textarea required minLength={10} maxLength={5000} rows={6} className={`${cls} py-3`} value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })} /></label><button disabled={status === "loading"} className="min-h-12 rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 px-5 font-semibold disabled:opacity-60">{status === "loading" ? "Sending your message…" : "Send Message"}</button>{status === "success" && <p role="status" className="text-sm text-emerald-300">Your message has been sent.</p>}{error && <p role="alert" className="text-sm text-rose-200">{error}</p>}</form>;
}
