export type LanguageCode =
  | "english"
  | "hindi"
  | "hinglish"
  | "bengali"
  | "marathi"
  | "tamil"
  | "telugu"
  | "gujarati"
  | "punjabi";

export const LANGUAGE_STORAGE_KEY = "bhagya_selected_language_v1";
export const LANGUAGE_DEFAULT_MIGRATION_KEY =
  "bhagya_default_language_english_v1";
export const DEFAULT_LANGUAGE_CODE: LanguageCode = "english";

export const languages = [
  { code: "hinglish", label: "Hinglish", short: "HIN" },
  { code: "english", label: "English", short: "EN" },
  { code: "hindi", label: "Hindi", short: "HI" },
  { code: "bengali", label: "Bengali", short: "BN" },
  { code: "marathi", label: "Marathi", short: "MR" },
  { code: "tamil", label: "Tamil", short: "TA" },
  { code: "telugu", label: "Telugu", short: "TE" },
  { code: "gujarati", label: "Gujarati", short: "GU" },
  { code: "punjabi", label: "Punjabi", short: "PA" },
] as const;

export type UiText = {
  appName: string;
  tagline: string;
  badge: string;
  headlineLine1: string;
  headlineLine2: string;
  subtitle: string;
  inputPlaceholder: string;
  followupPlaceholder: string;
  ask: string;
  signIn: string;
  logout: string;
  newReading: string;
  recent: string;
  recentReadings: string;
  noReadingsYet: string;
  reading: string;
  consulting: string;
  cosmicError: string;
  silentError: string;
  closeDrawer: string;
  attach: string;
  back: string;
  welcomeBack: string;
  createAccount: string;
  authBadge: string;
  loginDescription: string;
  signupDescription: string;
  fullName: string;
  enterName: string;
  email: string;
  password: string;
  enterPassword: string;
  forgot: string;
  show: string;
  hide: string;
  login: string;
  createAccountButton: string;
  continueWithGoogle: string;
  or: string;
  newToBhagya: string;
  alreadyHaveAccount: string;
  termsText: string;
  pleaseWait: string;
  loginSuccess: string;
  accountCreated: string;
  accountExists: string;
  confirmEmail: string;
  pleaseEnterEmailPassword: string;
  pleaseEnterName: string;
  authError: string;
  timeAgo: {
    justNow: string;
    minutes: string;
    hours: string;
    days: string;
  };
  services: {
    astrology: string;
    numerology: string;
    tarot: string;
    palmistry: string;
  };
};

export const UI_TEXT = {
  english: {
    appName: "Bhagya.ai",
    tagline: "AI Spiritual Guidance",
    badge: "Astrology · Numerology · Tarot · Palmistry",
    headlineLine1: "What guidance do you",
    headlineLine2: "need today?",
    subtitle: "Ask about career, love, destiny, or your cosmic path",
    inputPlaceholder: "Ask about career, love, marriage, kundli…",
    followupPlaceholder: "Ask a follow-up question…",
    ask: "Ask",
    signIn: "Sign in",
    logout: "Logout",
    newReading: "New Reading",
    recent: "Recent",
    recentReadings: "Recent readings",
    noReadingsYet: "No readings yet",
    reading: "Reading",
    consulting: "Consulting the cosmos…",
    cosmicError: "The cosmic connection wavered. Please try again in a moment.",
    silentError: "The stars are silent for now. Please try again.",
    closeDrawer: "Close drawer",
    attach: "Attach",
    back: "Back",
    welcomeBack: "Welcome back",
    createAccount: "Create your account",
    authBadge: "Your personal spiritual guidance account",
    loginDescription: "Continue your Bhagya.ai readings and spiritual guidance journey.",
    signupDescription: "Save your readings, recent messages, and personal guidance history.",
    fullName: "Full Name",
    enterName: "Enter your name",
    email: "Email",
    password: "Password",
    enterPassword: "Enter password",
    forgot: "Forgot?",
    show: "Show",
    hide: "Hide",
    login: "Login",
    createAccountButton: "Create Account",
    continueWithGoogle: "Continue with Google",
    or: "or",
    newToBhagya: "New to Bhagya.ai?",
    alreadyHaveAccount: "Already have an account?",
    termsText: "By continuing, you agree that Bhagya.ai provides spiritual guidance for self-reflection and entertainment.",
    pleaseWait: "Please wait…",
    loginSuccess: "Login successful. Redirecting…",
    accountCreated: "Account created successfully. Redirecting…",
    accountExists: "This email is already registered with Bhagya.ai. Please login instead.",
    confirmEmail: "Account created. Please check your email to confirm your account, then login.",
    pleaseEnterEmailPassword: "Please enter your email and password.",
    pleaseEnterName: "Please enter your name.",
    authError: "Something went wrong. Please try again.",
    timeAgo: { justNow: "just now", minutes: "{count}m ago", hours: "{count}h ago", days: "{count}d ago" },
    services: { astrology: "Astrology", numerology: "Numerology", tarot: "Tarot", palmistry: "Palmistry" },
  },
  hindi: {
    appName: "Bhagya.ai",
    tagline: "AI आध्यात्मिक मार्गदर्शन",
    badge: "ज्योतिष · अंक ज्योतिष · टैरो · हस्तरेखा",
    headlineLine1: "आज आपको किस",
    headlineLine2: "मार्गदर्शन की ज़रूरत है?",
    subtitle: "करियर, प्रेम, भाग्य या अपने आध्यात्मिक मार्ग के बारे में पूछें",
    inputPlaceholder: "करियर, प्रेम, विवाह, कुंडली के बारे में पूछें…",
    followupPlaceholder: "अगला सवाल पूछें…",
    ask: "पूछें",
    signIn: "साइन इन",
    logout: "लॉगआउट",
    newReading: "नई रीडिंग",
    recent: "हाल की",
    recentReadings: "हाल की रीडिंग",
    noReadingsYet: "अभी कोई रीडिंग नहीं",
    reading: "रीडिंग",
    consulting: "ब्रह्मांड से संकेत लिए जा रहे हैं…",
    cosmicError: "ब्रह्मांडीय संपर्क रुक गया। कृपया थोड़ी देर बाद फिर कोशिश करें।",
    silentError: "अभी सितारे शांत हैं। कृपया फिर कोशिश करें।",
    closeDrawer: "दराज़ बंद करें",
    attach: "जोड़ें",
    back: "वापस",
    welcomeBack: "फिर से स्वागत है",
    createAccount: "अपना खाता बनाएँ",
    authBadge: "आपका निजी आध्यात्मिक मार्गदर्शन खाता",
    loginDescription: "अपनी Bhagya.ai रीडिंग और आध्यात्मिक यात्रा जारी रखें।",
    signupDescription: "अपनी रीडिंग, हाल के संदेश और निजी मार्गदर्शन इतिहास सहेजें।",
    fullName: "पूरा नाम",
    enterName: "अपना नाम लिखें",
    email: "ईमेल",
    password: "पासवर्ड",
    enterPassword: "पासवर्ड लिखें",
    forgot: "भूल गए?",
    show: "दिखाएँ",
    hide: "छिपाएँ",
    login: "लॉगिन",
    createAccountButton: "खाता बनाएँ",
    continueWithGoogle: "Google से जारी रखें",
    or: "या",
    newToBhagya: "Bhagya.ai पर नए हैं?",
    alreadyHaveAccount: "पहले से खाता है?",
    termsText: "जारी रखकर आप सहमत हैं कि Bhagya.ai आत्मचिंतन और मनोरंजन के लिए आध्यात्मिक मार्गदर्शन देता है।",
    pleaseWait: "कृपया प्रतीक्षा करें…",
    loginSuccess: "लॉगिन सफल। आगे बढ़ रहे हैं…",
    accountCreated: "खाता बन गया। आगे बढ़ रहे हैं…",
    accountExists: "यह ईमेल Bhagya.ai पर पहले से पंजीकृत है। कृपया लॉगिन करें।",
    confirmEmail: "खाता बन गया। कृपया ईमेल से पुष्टि करें, फिर लॉगिन करें।",
    pleaseEnterEmailPassword: "कृपया ईमेल और पासवर्ड लिखें।",
    pleaseEnterName: "कृपया अपना नाम लिखें।",
    authError: "कुछ गलत हुआ। कृपया फिर कोशिश करें।",
    timeAgo: { justNow: "अभी", minutes: "{count} मि. पहले", hours: "{count} घं. पहले", days: "{count} दिन पहले" },
    services: { astrology: "ज्योतिष", numerology: "अंक ज्योतिष", tarot: "टैरो", palmistry: "हस्तरेखा" },
  },
  hinglish: {
    appName: "Bhagya.ai",
    tagline: "AI Spiritual Guidance",
    badge: "Jyotish · Numerology · Tarot · Palmistry",
    headlineLine1: "Aaj aapko kis",
    headlineLine2: "guidance ki zaroorat hai?",
    subtitle: "Career, love, destiny ya apne cosmic path ke baare mein poochhein",
    inputPlaceholder: "Career, love, marriage, kundli ke baare mein poochhein…",
    followupPlaceholder: "Agla sawaal poochhein…",
    ask: "Poochhein",
    signIn: "Sign in",
    logout: "Logout",
    newReading: "Nayi Reading",
    recent: "Recent",
    recentReadings: "Recent readings",
    noReadingsYet: "Abhi koi reading nahi",
    reading: "Reading",
    consulting: "Cosmos se guidance li ja rahi hai…",
    cosmicError: "Cosmic connection ruk gaya. Thodi der mein phir try karein.",
    silentError: "Abhi stars silent hain. Please phir try karein.",
    closeDrawer: "Drawer band karein",
    attach: "Attach",
    back: "Back",
    welcomeBack: "Welcome back",
    createAccount: "Apna account banayein",
    authBadge: "Aapka personal spiritual guidance account",
    loginDescription: "Apni Bhagya.ai readings aur spiritual journey continue karein.",
    signupDescription: "Apni readings, recent messages aur personal guidance history save karein.",
    fullName: "Full Name",
    enterName: "Apna naam enter karein",
    email: "Email",
    password: "Password",
    enterPassword: "Password enter karein",
    forgot: "Bhool gaye?",
    show: "Show",
    hide: "Hide",
    login: "Login",
    createAccountButton: "Account Banayein",
    continueWithGoogle: "Google se continue karein",
    or: "ya",
    newToBhagya: "Bhagya.ai par naye hain?",
    alreadyHaveAccount: "Pehle se account hai?",
    termsText: "Continue karke aap maante hain ki Bhagya.ai self-reflection aur entertainment ke liye spiritual guidance deta hai.",
    pleaseWait: "Please wait…",
    loginSuccess: "Login successful. Redirect ho raha hai…",
    accountCreated: "Account ban gaya. Redirect ho raha hai…",
    accountExists: "Yeh email Bhagya.ai par pehle se registered hai. Please login karein.",
    confirmEmail: "Account ban gaya. Email confirm karke login karein.",
    pleaseEnterEmailPassword: "Please email aur password enter karein.",
    pleaseEnterName: "Please apna naam enter karein.",
    authError: "Kuch galat ho gaya. Please phir try karein.",
    timeAgo: { justNow: "abhi", minutes: "{count}m pehle", hours: "{count}h pehle", days: "{count}d pehle" },
    services: { astrology: "Jyotish", numerology: "Numerology", tarot: "Tarot", palmistry: "Palmistry" },
  },
  bengali: {
    appName: "Bhagya.ai",
    tagline: "AI আধ্যাত্মিক নির্দেশনা",
    badge: "জ্যোতিষ · সংখ্যাতত্ত্ব · ট্যারো · হস্তরেখা",
    headlineLine1: "আজ আপনার কী",
    headlineLine2: "নির্দেশনা দরকার?",
    subtitle: "কর্মজীবন, ভালোবাসা, ভাগ্য বা আপনার আধ্যাত্মিক পথ নিয়ে জিজ্ঞাসা করুন",
    inputPlaceholder: "কর্মজীবন, ভালোবাসা, বিয়ে, কুণ্ডলী নিয়ে জিজ্ঞাসা করুন…",
    followupPlaceholder: "পরের প্রশ্নটি করুন…",
    ask: "জিজ্ঞাসা করুন",
    signIn: "সাইন ইন",
    logout: "লগআউট",
    newReading: "নতুন রিডিং",
    recent: "সাম্প্রতিক",
    recentReadings: "সাম্প্রতিক রিডিং",
    noReadingsYet: "এখনও কোনো রিডিং নেই",
    reading: "রিডিং",
    consulting: "মহাজগতের ইঙ্গিত নেওয়া হচ্ছে…",
    cosmicError: "মহাজাগতিক সংযোগ থেমে গেছে। একটু পরে আবার চেষ্টা করুন।",
    silentError: "তারারা এখন নীরব। আবার চেষ্টা করুন।",
    closeDrawer: "ড্রয়ার বন্ধ করুন",
    attach: "যুক্ত করুন",
    back: "ফিরে যান",
    welcomeBack: "আবার স্বাগতম",
    createAccount: "আপনার অ্যাকাউন্ট তৈরি করুন",
    authBadge: "আপনার ব্যক্তিগত আধ্যাত্মিক নির্দেশনা অ্যাকাউন্ট",
    loginDescription: "আপনার Bhagya.ai রিডিং ও আধ্যাত্মিক যাত্রা চালিয়ে যান।",
    signupDescription: "আপনার রিডিং, সাম্প্রতিক বার্তা ও ব্যক্তিগত নির্দেশনার ইতিহাস সংরক্ষণ করুন।",
    fullName: "পুরো নাম",
    enterName: "আপনার নাম লিখুন",
    email: "ইমেইল",
    password: "পাসওয়ার্ড",
    enterPassword: "পাসওয়ার্ড লিখুন",
    forgot: "ভুলে গেছেন?",
    show: "দেখান",
    hide: "লুকান",
    login: "লগইন",
    createAccountButton: "অ্যাকাউন্ট তৈরি করুন",
    continueWithGoogle: "Google দিয়ে চালিয়ে যান",
    or: "অথবা",
    newToBhagya: "Bhagya.ai-তে নতুন?",
    alreadyHaveAccount: "আগেই অ্যাকাউন্ট আছে?",
    termsText: "চালিয়ে গেলে আপনি সম্মত হচ্ছেন যে Bhagya.ai আত্মবিশ্লেষণ ও বিনোদনের জন্য আধ্যাত্মিক নির্দেশনা দেয়।",
    pleaseWait: "অনুগ্রহ করে অপেক্ষা করুন…",
    loginSuccess: "লগইন সফল। এগিয়ে নেওয়া হচ্ছে…",
    accountCreated: "অ্যাকাউন্ট তৈরি হয়েছে। এগিয়ে নেওয়া হচ্ছে…",
    accountExists: "এই ইমেইল Bhagya.ai-তে আগে থেকেই নিবন্ধিত। অনুগ্রহ করে লগইন করুন।",
    confirmEmail: "অ্যাকাউন্ট তৈরি হয়েছে। ইমেইল নিশ্চিত করে তারপর লগইন করুন।",
    pleaseEnterEmailPassword: "অনুগ্রহ করে ইমেইল ও পাসওয়ার্ড লিখুন।",
    pleaseEnterName: "অনুগ্রহ করে আপনার নাম লিখুন।",
    authError: "কিছু ভুল হয়েছে। আবার চেষ্টা করুন।",
    timeAgo: { justNow: "এইমাত্র", minutes: "{count} মি. আগে", hours: "{count} ঘণ্টা আগে", days: "{count} দিন আগে" },
    services: { astrology: "জ্যোতিষ", numerology: "সংখ্যাতত্ত্ব", tarot: "ট্যারো", palmistry: "হস্তরেখা" },
  },
  marathi: {
    appName: "Bhagya.ai",
    tagline: "AI आध्यात्मिक मार्गदर्शन",
    badge: "ज्योतिष · अंकशास्त्र · टॅरो · हस्तरेषा",
    headlineLine1: "आज तुम्हाला कोणत्या",
    headlineLine2: "मार्गदर्शनाची गरज आहे?",
    subtitle: "करिअर, प्रेम, नशीब किंवा तुमच्या आध्यात्मिक मार्गाबद्दल विचारा",
    inputPlaceholder: "करिअर, प्रेम, विवाह, कुंडलीबद्दल विचारा…",
    followupPlaceholder: "पुढचा प्रश्न विचारा…",
    ask: "विचारा",
    signIn: "साइन इन",
    logout: "लॉगआउट",
    newReading: "नवीन रीडिंग",
    recent: "अलीकडील",
    recentReadings: "अलीकडील रीडिंग",
    noReadingsYet: "अजून कोणतेही रीडिंग नाही",
    reading: "रीडिंग",
    consulting: "विश्वाचे संकेत घेत आहोत…",
    cosmicError: "विश्वाशी संपर्क थांबला. कृपया थोड्या वेळाने पुन्हा प्रयत्न करा.",
    silentError: "तारे सध्या शांत आहेत. कृपया पुन्हा प्रयत्न करा.",
    closeDrawer: "ड्रॉवर बंद करा",
    attach: "जोडा",
    back: "मागे",
    welcomeBack: "पुन्हा स्वागत आहे",
    createAccount: "तुमचे खाते तयार करा",
    authBadge: "तुमचे वैयक्तिक आध्यात्मिक मार्गदर्शन खाते",
    loginDescription: "तुमची Bhagya.ai रीडिंग आणि आध्यात्मिक यात्रा सुरू ठेवा.",
    signupDescription: "तुमची रीडिंग, अलीकडील संदेश आणि वैयक्तिक मार्गदर्शन इतिहास जतन करा.",
    fullName: "पूर्ण नाव",
    enterName: "तुमचे नाव लिहा",
    email: "ईमेल",
    password: "पासवर्ड",
    enterPassword: "पासवर्ड लिहा",
    forgot: "विसरलात?",
    show: "दाखवा",
    hide: "लपवा",
    login: "लॉगिन",
    createAccountButton: "खाते तयार करा",
    continueWithGoogle: "Google सह पुढे जा",
    or: "किंवा",
    newToBhagya: "Bhagya.ai वर नवीन आहात?",
    alreadyHaveAccount: "आधीच खाते आहे?",
    termsText: "पुढे जाऊन तुम्ही मान्य करता की Bhagya.ai आत्मचिंतन आणि मनोरंजनासाठी आध्यात्मिक मार्गदर्शन देते.",
    pleaseWait: "कृपया थांबा…",
    loginSuccess: "लॉगिन यशस्वी. पुढे नेत आहोत…",
    accountCreated: "खाते तयार झाले. पुढे नेत आहोत…",
    accountExists: "हा ईमेल Bhagya.ai वर आधीच नोंदणीकृत आहे. कृपया लॉगिन करा.",
    confirmEmail: "खाते तयार झाले. कृपया ईमेलची पुष्टी करून लॉगिन करा.",
    pleaseEnterEmailPassword: "कृपया ईमेल आणि पासवर्ड लिहा.",
    pleaseEnterName: "कृपया तुमचे नाव लिहा.",
    authError: "काहीतरी चुकले. कृपया पुन्हा प्रयत्न करा.",
    timeAgo: { justNow: "आत्ताच", minutes: "{count} मि. पूर्वी", hours: "{count} ता. पूर्वी", days: "{count} दिवसांपूर्वी" },
    services: { astrology: "ज्योतिष", numerology: "अंकशास्त्र", tarot: "टॅरो", palmistry: "हस्तरेषा" },
  },
  tamil: {
    appName: "Bhagya.ai",
    tagline: "AI ஆன்மிக வழிகாட்டுதல்",
    badge: "ஜோதிடம் · எண் கணிதம் · டாரோ · கைரேகை",
    headlineLine1: "இன்று உங்களுக்கு என்ன",
    headlineLine2: "வழிகாட்டுதல் தேவை?",
    subtitle: "தொழில், காதல், விதி அல்லது உங்கள் ஆன்மிகப் பாதை பற்றி கேளுங்கள்",
    inputPlaceholder: "தொழில், காதல், திருமணம், ஜாதகம் பற்றி கேளுங்கள்…",
    followupPlaceholder: "அடுத்த கேள்வியைக் கேளுங்கள்…",
    ask: "கேளுங்கள்",
    signIn: "உள்நுழைக",
    logout: "வெளியேறு",
    newReading: "புதிய வாசிப்பு",
    recent: "சமீபத்தியவை",
    recentReadings: "சமீபத்திய வாசிப்புகள்",
    noReadingsYet: "இன்னும் வாசிப்புகள் இல்லை",
    reading: "வாசிப்பு",
    consulting: "பிரபஞ்சத்தின் அறிகுறிகள் பார்க்கப்படுகின்றன…",
    cosmicError: "பிரபஞ்சத் தொடர்பு தடைப்பட்டது. சிறிது நேரம் கழித்து மீண்டும் முயலுங்கள்.",
    silentError: "நட்சத்திரங்கள் இப்போது அமைதியாக உள்ளன. மீண்டும் முயலுங்கள்.",
    closeDrawer: "பக்கப்பட்டியை மூடு",
    attach: "இணைக்கவும்",
    back: "பின்செல்",
    welcomeBack: "மீண்டும் வரவேற்கிறோம்",
    createAccount: "உங்கள் கணக்கை உருவாக்குங்கள்",
    authBadge: "உங்கள் தனிப்பட்ட ஆன்மிக வழிகாட்டுதல் கணக்கு",
    loginDescription: "உங்கள் Bhagya.ai வாசிப்புகளையும் ஆன்மிகப் பயணத்தையும் தொடருங்கள்.",
    signupDescription: "உங்கள் வாசிப்புகள், சமீபத்திய செய்திகள் மற்றும் தனிப்பட்ட வழிகாட்டுதல் வரலாற்றைச் சேமியுங்கள்.",
    fullName: "முழுப் பெயர்",
    enterName: "உங்கள் பெயரை உள்ளிடுங்கள்",
    email: "மின்னஞ்சல்",
    password: "கடவுச்சொல்",
    enterPassword: "கடவுச்சொல்லை உள்ளிடுங்கள்",
    forgot: "மறந்துவிட்டதா?",
    show: "காட்டு",
    hide: "மறை",
    login: "உள்நுழைக",
    createAccountButton: "கணக்கை உருவாக்கு",
    continueWithGoogle: "Google மூலம் தொடருங்கள்",
    or: "அல்லது",
    newToBhagya: "Bhagya.ai-க்கு புதியவரா?",
    alreadyHaveAccount: "ஏற்கனவே கணக்கு உள்ளதா?",
    termsText: "தொடர்வதன் மூலம், Bhagya.ai சுயபரிசீலனை மற்றும் பொழுதுபோக்கிற்கான ஆன்மிக வழிகாட்டுதலை வழங்குகிறது என்பதை ஏற்கிறீர்கள்.",
    pleaseWait: "தயவுசெய்து காத்திருக்கவும்…",
    loginSuccess: "உள்நுழைவு வெற்றி. திருப்பி அனுப்பப்படுகிறது…",
    accountCreated: "கணக்கு உருவாக்கப்பட்டது. திருப்பி அனுப்பப்படுகிறது…",
    accountExists: "இந்த மின்னஞ்சல் Bhagya.ai-ல் ஏற்கனவே பதிவு செய்யப்பட்டுள்ளது. உள்நுழையுங்கள்.",
    confirmEmail: "கணக்கு உருவாக்கப்பட்டது. மின்னஞ்சலை உறுதிப்படுத்தி உள்நுழையுங்கள்.",
    pleaseEnterEmailPassword: "மின்னஞ்சல் மற்றும் கடவுச்சொல்லை உள்ளிடுங்கள்.",
    pleaseEnterName: "உங்கள் பெயரை உள்ளிடுங்கள்.",
    authError: "ஏதோ தவறு ஏற்பட்டது. மீண்டும் முயலுங்கள்.",
    timeAgo: { justNow: "இப்போது", minutes: "{count} நிமி. முன்", hours: "{count} மணி முன்", days: "{count} நாள் முன்" },
    services: { astrology: "ஜோதிடம்", numerology: "எண் கணிதம்", tarot: "டாரோ", palmistry: "கைரேகை" },
  },
  telugu: {
    appName: "Bhagya.ai",
    tagline: "AI ఆధ్యాత్మిక మార్గదర్శనం",
    badge: "జ్యోతిష్యం · సంఖ్యాశాస్త్రం · టారో · హస్తసాముద్రికం",
    headlineLine1: "ఈ రోజు మీకు ఏ",
    headlineLine2: "మార్గదర్శనం కావాలి?",
    subtitle: "వృత్తి, ప్రేమ, విధి లేదా మీ ఆధ్యాత్మిక మార్గం గురించి అడగండి",
    inputPlaceholder: "వృత్తి, ప్రేమ, వివాహం, జాతకం గురించి అడగండి…",
    followupPlaceholder: "తదుపరి ప్రశ్న అడగండి…",
    ask: "అడగండి",
    signIn: "సైన్ ఇన్",
    logout: "లాగౌట్",
    newReading: "కొత్త రీడింగ్",
    recent: "ఇటీవలి",
    recentReadings: "ఇటీవలి రీడింగ్స్",
    noReadingsYet: "ఇంకా రీడింగ్స్ లేవు",
    reading: "రీడింగ్",
    consulting: "విశ్వ సంకేతాలను పరిశీలిస్తున్నాం…",
    cosmicError: "విశ్వంతో సంబంధం నిలిచింది. కాసేపటి తర్వాత మళ్లీ ప్రయత్నించండి.",
    silentError: "నక్షత్రాలు ఇప్పుడు నిశ్శబ్దంగా ఉన్నాయి. మళ్లీ ప్రయత్నించండి.",
    closeDrawer: "డ్రాయర్ మూసివేయండి",
    attach: "జోడించండి",
    back: "వెనుకకు",
    welcomeBack: "మళ్లీ స్వాగతం",
    createAccount: "మీ ఖాతాను సృష్టించండి",
    authBadge: "మీ వ్యక్తిగత ఆధ్యాత్మిక మార్గదర్శక ఖాతా",
    loginDescription: "మీ Bhagya.ai రీడింగ్స్ మరియు ఆధ్యాత్మిక ప్రయాణాన్ని కొనసాగించండి.",
    signupDescription: "మీ రీడింగ్స్, ఇటీవలి సందేశాలు మరియు వ్యక్తిగత మార్గదర్శక చరిత్రను సేవ్ చేయండి.",
    fullName: "పూర్తి పేరు",
    enterName: "మీ పేరు నమోదు చేయండి",
    email: "ఇమెయిల్",
    password: "పాస్‌వర్డ్",
    enterPassword: "పాస్‌వర్డ్ నమోదు చేయండి",
    forgot: "మర్చిపోయారా?",
    show: "చూపు",
    hide: "దాచు",
    login: "లాగిన్",
    createAccountButton: "ఖాతా సృష్టించండి",
    continueWithGoogle: "Googleతో కొనసాగండి",
    or: "లేదా",
    newToBhagya: "Bhagya.aiకి కొత్తవారా?",
    alreadyHaveAccount: "ఇప్పటికే ఖాతా ఉందా?",
    termsText: "కొనసాగడం ద్వారా Bhagya.ai స్వీయ పరిశీలన మరియు వినోదం కోసం ఆధ్యాత్మిక మార్గదర్శనం ఇస్తుందని మీరు అంగీకరిస్తున్నారు.",
    pleaseWait: "దయచేసి వేచి ఉండండి…",
    loginSuccess: "లాగిన్ విజయవంతం. మళ్లిస్తున్నాం…",
    accountCreated: "ఖాతా సృష్టించబడింది. మళ్లిస్తున్నాం…",
    accountExists: "ఈ ఇమెయిల్ Bhagya.aiలో ఇప్పటికే నమోదైంది. దయచేసి లాగిన్ చేయండి.",
    confirmEmail: "ఖాతా సృష్టించబడింది. ఇమెయిల్ నిర్ధారించి లాగిన్ చేయండి.",
    pleaseEnterEmailPassword: "దయచేసి ఇమెయిల్ మరియు పాస్‌వర్డ్ నమోదు చేయండి.",
    pleaseEnterName: "దయచేసి మీ పేరు నమోదు చేయండి.",
    authError: "ఏదో తప్పు జరిగింది. మళ్లీ ప్రయత్నించండి.",
    timeAgo: { justNow: "ఇప్పుడే", minutes: "{count} ని. క్రితం", hours: "{count} గం. క్రితం", days: "{count} రోజుల క్రితం" },
    services: { astrology: "జ్యోతిష్యం", numerology: "సంఖ్యాశాస్త్రం", tarot: "టారో", palmistry: "హస్తసాముద్రికం" },
  },
  gujarati: {
    appName: "Bhagya.ai",
    tagline: "AI આધ્યાત્મિક માર્ગદર્શન",
    badge: "જ્યોતિષ · અંકશાસ્ત્ર · ટેરો · હસ્તરેખા",
    headlineLine1: "આજે તમને કયા",
    headlineLine2: "માર્ગદર્શનની જરૂર છે?",
    subtitle: "કારકિર્દી, પ્રેમ, ભાગ્ય અથવા તમારા આધ્યાત્મિક માર્ગ વિશે પૂછો",
    inputPlaceholder: "કારકિર્દી, પ્રેમ, લગ્ન, કુંડળી વિશે પૂછો…",
    followupPlaceholder: "આગળનો પ્રશ્ન પૂછો…",
    ask: "પૂછો",
    signIn: "સાઇન ઇન",
    logout: "લૉગઆઉટ",
    newReading: "નવી રીડિંગ",
    recent: "તાજેતરની",
    recentReadings: "તાજેતરની રીડિંગ્સ",
    noReadingsYet: "હજુ કોઈ રીડિંગ નથી",
    reading: "રીડિંગ",
    consulting: "બ્રહ્માંડના સંકેતો જોવાઈ રહ્યા છે…",
    cosmicError: "બ્રહ્માંડ સાથેનો સંપર્ક અટક્યો. થોડીવાર પછી ફરી પ્રયાસ કરો.",
    silentError: "તારાઓ અત્યારે શાંત છે. ફરી પ્રયાસ કરો.",
    closeDrawer: "ડ્રોઅર બંધ કરો",
    attach: "જોડો",
    back: "પાછા",
    welcomeBack: "ફરી સ્વાગત છે",
    createAccount: "તમારું ખાતું બનાવો",
    authBadge: "તમારું વ્યક્તિગત આધ્યાત્મિક માર્ગદર્શન ખાતું",
    loginDescription: "તમારી Bhagya.ai રીડિંગ્સ અને આધ્યાત્મિક યાત્રા ચાલુ રાખો.",
    signupDescription: "તમારી રીડિંગ્સ, તાજેતરના સંદેશા અને વ્યક્તિગત માર્ગદર્શન ઇતિહાસ સાચવો.",
    fullName: "પૂરું નામ",
    enterName: "તમારું નામ લખો",
    email: "ઈમેલ",
    password: "પાસવર્ડ",
    enterPassword: "પાસવર્ડ લખો",
    forgot: "ભૂલી ગયા?",
    show: "બતાવો",
    hide: "છુપાવો",
    login: "લૉગિન",
    createAccountButton: "ખાતું બનાવો",
    continueWithGoogle: "Google સાથે આગળ વધો",
    or: "અથવા",
    newToBhagya: "Bhagya.ai પર નવા છો?",
    alreadyHaveAccount: "પહેલેથી ખાતું છે?",
    termsText: "આગળ વધીને તમે સંમત થાઓ છો કે Bhagya.ai આત્મચિંતન અને મનોરંજન માટે આધ્યાત્મિક માર્ગદર્શન આપે છે.",
    pleaseWait: "કૃપા કરીને રાહ જુઓ…",
    loginSuccess: "લૉગિન સફળ. આગળ લઈ જઈ રહ્યા છીએ…",
    accountCreated: "ખાતું બની ગયું. આગળ લઈ જઈ રહ્યા છીએ…",
    accountExists: "આ ઈમેલ Bhagya.ai પર પહેલેથી નોંધાયેલ છે. કૃપા કરીને લૉગિન કરો.",
    confirmEmail: "ખાતું બની ગયું. ઈમેલની પુષ્ટિ કરીને લૉગિન કરો.",
    pleaseEnterEmailPassword: "કૃપા કરીને ઈમેલ અને પાસવર્ડ લખો.",
    pleaseEnterName: "કૃપા કરીને તમારું નામ લખો.",
    authError: "કંઈક ખોટું થયું. ફરી પ્રયાસ કરો.",
    timeAgo: { justNow: "હમણાં", minutes: "{count} મિ. પહેલાં", hours: "{count} ક. પહેલાં", days: "{count} દિવસ પહેલાં" },
    services: { astrology: "જ્યોતિષ", numerology: "અંકશાસ્ત્ર", tarot: "ટેરો", palmistry: "હસ્તરેખા" },
  },
  punjabi: {
    appName: "Bhagya.ai",
    tagline: "AI ਰੂਹਾਨੀ ਮਾਰਗਦਰਸ਼ਨ",
    badge: "ਜੋਤਿਸ਼ · ਅੰਕ ਵਿਗਿਆਨ · ਟੈਰੋ · ਹਸਤਰੇਖਾ",
    headlineLine1: "ਅੱਜ ਤੁਹਾਨੂੰ ਕਿਸ",
    headlineLine2: "ਮਾਰਗਦਰਸ਼ਨ ਦੀ ਲੋੜ ਹੈ?",
    subtitle: "ਕਰੀਅਰ, ਪਿਆਰ, ਕਿਸਮਤ ਜਾਂ ਆਪਣੇ ਰੂਹਾਨੀ ਰਾਹ ਬਾਰੇ ਪੁੱਛੋ",
    inputPlaceholder: "ਕਰੀਅਰ, ਪਿਆਰ, ਵਿਆਹ, ਕੁੰਡਲੀ ਬਾਰੇ ਪੁੱਛੋ…",
    followupPlaceholder: "ਅਗਲਾ ਸਵਾਲ ਪੁੱਛੋ…",
    ask: "ਪੁੱਛੋ",
    signIn: "ਸਾਈਨ ਇਨ",
    logout: "ਲੌਗਆਉਟ",
    newReading: "ਨਵੀਂ ਰੀਡਿੰਗ",
    recent: "ਹਾਲੀਆ",
    recentReadings: "ਹਾਲੀਆ ਰੀਡਿੰਗਾਂ",
    noReadingsYet: "ਹਾਲੇ ਕੋਈ ਰੀਡਿੰਗ ਨਹੀਂ",
    reading: "ਰੀਡਿੰਗ",
    consulting: "ਬ੍ਰਹਿਮੰਡ ਦੇ ਸੰਕੇਤ ਵੇਖੇ ਜਾ ਰਹੇ ਹਨ…",
    cosmicError: "ਬ੍ਰਹਿਮੰਡ ਨਾਲ ਸੰਪਰਕ ਰੁਕ ਗਿਆ। ਥੋੜ੍ਹੀ ਦੇਰ ਬਾਅਦ ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    silentError: "ਤਾਰੇ ਇਸ ਵੇਲੇ ਚੁੱਪ ਹਨ। ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    closeDrawer: "ਦਰਾਜ਼ ਬੰਦ ਕਰੋ",
    attach: "ਜੋੜੋ",
    back: "ਪਿੱਛੇ",
    welcomeBack: "ਮੁੜ ਜੀ ਆਇਆਂ ਨੂੰ",
    createAccount: "ਆਪਣਾ ਖਾਤਾ ਬਣਾਓ",
    authBadge: "ਤੁਹਾਡਾ ਨਿੱਜੀ ਰੂਹਾਨੀ ਮਾਰਗਦਰਸ਼ਨ ਖਾਤਾ",
    loginDescription: "ਆਪਣੀਆਂ Bhagya.ai ਰੀਡਿੰਗਾਂ ਅਤੇ ਰੂਹਾਨੀ ਯਾਤਰਾ ਜਾਰੀ ਰੱਖੋ।",
    signupDescription: "ਆਪਣੀਆਂ ਰੀਡਿੰਗਾਂ, ਹਾਲੀਆ ਸੁਨੇਹੇ ਅਤੇ ਨਿੱਜੀ ਮਾਰਗਦਰਸ਼ਨ ਦਾ ਇਤਿਹਾਸ ਸੰਭਾਲੋ।",
    fullName: "ਪੂਰਾ ਨਾਮ",
    enterName: "ਆਪਣਾ ਨਾਮ ਲਿਖੋ",
    email: "ਈਮੇਲ",
    password: "ਪਾਸਵਰਡ",
    enterPassword: "ਪਾਸਵਰਡ ਲਿਖੋ",
    forgot: "ਭੁੱਲ ਗਏ?",
    show: "ਵਿਖਾਓ",
    hide: "ਲੁਕਾਓ",
    login: "ਲੌਗਿਨ",
    createAccountButton: "ਖਾਤਾ ਬਣਾਓ",
    continueWithGoogle: "Google ਨਾਲ ਜਾਰੀ ਰੱਖੋ",
    or: "ਜਾਂ",
    newToBhagya: "Bhagya.ai ਉੱਤੇ ਨਵੇਂ ਹੋ?",
    alreadyHaveAccount: "ਪਹਿਲਾਂ ਹੀ ਖਾਤਾ ਹੈ?",
    termsText: "ਜਾਰੀ ਰੱਖ ਕੇ ਤੁਸੀਂ ਸਹਿਮਤ ਹੋ ਕਿ Bhagya.ai ਆਤਮ-ਚਿੰਤਨ ਅਤੇ ਮਨੋਰੰਜਨ ਲਈ ਰੂਹਾਨੀ ਮਾਰਗਦਰਸ਼ਨ ਦਿੰਦਾ ਹੈ।",
    pleaseWait: "ਕਿਰਪਾ ਕਰਕੇ ਉਡੀਕੋ…",
    loginSuccess: "ਲੌਗਿਨ ਸਫਲ। ਅੱਗੇ ਲਿਜਾਇਆ ਜਾ ਰਿਹਾ ਹੈ…",
    accountCreated: "ਖਾਤਾ ਬਣ ਗਿਆ। ਅੱਗੇ ਲਿਜਾਇਆ ਜਾ ਰਿਹਾ ਹੈ…",
    accountExists: "ਇਹ ਈਮੇਲ Bhagya.ai ਉੱਤੇ ਪਹਿਲਾਂ ਹੀ ਰਜਿਸਟਰ ਹੈ। ਕਿਰਪਾ ਕਰਕੇ ਲੌਗਿਨ ਕਰੋ।",
    confirmEmail: "ਖਾਤਾ ਬਣ ਗਿਆ। ਈਮੇਲ ਦੀ ਪੁਸ਼ਟੀ ਕਰਕੇ ਲੌਗਿਨ ਕਰੋ।",
    pleaseEnterEmailPassword: "ਕਿਰਪਾ ਕਰਕੇ ਈਮੇਲ ਅਤੇ ਪਾਸਵਰਡ ਲਿਖੋ।",
    pleaseEnterName: "ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਨਾਮ ਲਿਖੋ।",
    authError: "ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ। ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    timeAgo: { justNow: "ਹੁਣੇ", minutes: "{count} ਮਿੰਟ ਪਹਿਲਾਂ", hours: "{count} ਘੰਟੇ ਪਹਿਲਾਂ", days: "{count} ਦਿਨ ਪਹਿਲਾਂ" },
    services: { astrology: "ਜੋਤਿਸ਼", numerology: "ਅੰਕ ਵਿਗਿਆਨ", tarot: "ਟੈਰੋ", palmistry: "ਹਸਤਰੇਖਾ" },
  },
} satisfies Record<LanguageCode, UiText>;
