"use client";
import { useEffect, useRef, useState } from "react";
import type { ProfileData, BirthDetails } from "@/components/providers/SettingsProfileProvider";
import { supabase } from "@/lib/supabaseClient";

type BirthDetailsMode = "read-only-correction-available" | "editing" | "saving" | "permanently-locked" | "error";
type Draft = Pick<BirthDetails, "fullName" | "dateOfBirth" | "birthTime" | "birthTimeKnown" | "birthPlace">;

export default function BirthDetailsSettings({ profile, onUpdated }: { profile: ProfileData; onUpdated: (profile: ProfileData) => void }) {
  const original = profile.birthDetails!;
  const [mode, setMode] = useState<BirthDetailsMode>(original.correctionUsed ? "permanently-locked" : "read-only-correction-available");
  const [draft, setDraft] = useState<Draft>(original);
  const [confirmOpen, setConfirmOpen] = useState(false); const [confirmed, setConfirmed] = useState(false); const [error, setError] = useState("");
  const savingRef = useRef(false);
  useEffect(() => { setDraft(original); setMode(original.correctionUsed ? "permanently-locked" : "read-only-correction-available"); }, [original]);
  function cancel() { if (savingRef.current) return; setDraft(original); setError(""); setMode("read-only-correction-available"); }
  async function save() {
    if (!confirmed || savingRef.current) return;
    savingRef.current = true; setMode("saving"); setError("");
    try {
      const { data: { session } } = await supabase.auth.getSession();
      if (!session) throw new Error("Your session has expired. Please sign in again.");
      const response = await fetch("/api/birth-details/correct", { method: "PATCH", headers: { "Content-Type": "application/json", Authorization: `Bearer ${session.access_token}` }, body: JSON.stringify(draft) });
      const data = await response.json() as { birthDetails?: BirthDetails; message?: string };
      if (!response.ok || !data.birthDetails) throw new Error(data.message || "Your birth details could not be corrected. Your correction opportunity has not been used.");
      onUpdated({ ...profile, fullName: data.birthDetails.fullName, firstName: data.birthDetails.fullName.split(/\s+/)[0] || profile.firstName, birthDetails: data.birthDetails });
      setDraft(data.birthDetails); setConfirmOpen(false); setConfirmed(false); setMode("permanently-locked");
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Your birth details could not be corrected. Your correction opportunity has not been used."); setConfirmOpen(false); setConfirmed(false); setMode("error"); }
    finally { savingRef.current = false; }
  }
  const disabled = mode === "saving";
  return <div className="space-y-5">
    <div><h2 className="text-xl font-semibold">Birth Details</h2><p className="mt-1 text-sm leading-6 text-white/45">The permanent details used by your spiritual calculations.</p></div>
    {mode === "permanently-locked" ? <Notice title="Birth details are permanently locked">You have already used your one-time correction. These details can no longer be changed.</Notice> : <Notice title="One-time correction available">You can correct your birth details once if something was entered incorrectly. After the correction is saved, these details will be permanently locked.</Notice>}
    {error && <p role="alert" className="rounded-xl border border-rose-300/20 bg-rose-300/[.06] p-3 text-sm text-rose-100">{error}</p>}
    {(mode === "editing" || mode === "saving" || mode === "error") ? <div className="space-y-4"><Field label="Full name used for calculations" value={draft.fullName} disabled={disabled} onChange={(fullName) => setDraft({ ...draft, fullName })} maxLength={80} /><div className="grid gap-4 sm:grid-cols-2"><Field label="Date of birth" type="date" value={draft.dateOfBirth} disabled={disabled} max={new Date().toISOString().slice(0,10)} onChange={(dateOfBirth) => setDraft({ ...draft, dateOfBirth })} /><Field label="Birth time" type="time" value={draft.birthTime} disabled={disabled || !draft.birthTimeKnown} required={draft.birthTimeKnown} onChange={(birthTime) => setDraft({ ...draft, birthTime })} /></div><label className="flex items-center gap-2 text-sm text-white/65"><input type="checkbox" disabled={disabled} checked={!draft.birthTimeKnown} onChange={(e) => setDraft({ ...draft, birthTimeKnown: !e.target.checked, birthTime: e.target.checked ? "" : draft.birthTime })} /> I don’t know my exact birth time</label><Field label="Birth place" value={draft.birthPlace} disabled={disabled} maxLength={120} onChange={(birthPlace) => setDraft({ ...draft, birthPlace })} /><p className="rounded-xl border border-amber-300/15 bg-amber-300/[.05] p-3 text-sm leading-6 text-amber-100/70">Review every field carefully. A successful save permanently uses your one correction.</p><div className="flex flex-col-reverse gap-3 sm:flex-row"><button type="button" disabled={disabled} onClick={cancel} className="min-h-12 rounded-xl border border-white/10 px-5 font-medium disabled:opacity-40">Cancel</button><button type="button" disabled={disabled} onClick={() => { setConfirmOpen(true); setConfirmed(false); }} className="min-h-12 rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 px-5 font-semibold disabled:opacity-40">{disabled ? "Saving final correction…" : "Save Final Correction"}</button></div></div> : <><Rows details={original} />{mode === "read-only-correction-available" && <button type="button" onClick={() => setMode("editing")} className="min-h-12 rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 px-5 font-semibold">Correct Birth Details</button>}</>}
    {confirmOpen && <div className="fixed inset-0 z-[100] flex items-end justify-center overflow-y-auto bg-black/70 p-3 pb-[max(12px,env(safe-area-inset-bottom))] sm:items-center" role="dialog" aria-modal="true" aria-labelledby="birth-confirm-title"><div className="max-h-[calc(100dvh-24px)] w-full max-w-lg overflow-y-auto rounded-3xl border border-white/10 bg-[#071225] p-5 shadow-2xl sm:p-6"><h3 id="birth-confirm-title" className="text-xl font-semibold">Save your final correction?</h3><p className="mt-3 text-sm leading-6 text-white/55">Please review every detail carefully. Once saved, your birth details cannot be changed again from this account.</p><div className="mt-4"><Rows details={{ ...draft, correctionUsed: false, correctedAt: null }} /></div><label className="mt-5 flex items-start gap-3 rounded-xl border border-amber-300/15 bg-amber-300/[.05] p-3 text-sm leading-6 text-white/65"><input className="mt-1 h-4 w-4 shrink-0" type="checkbox" checked={confirmed} onChange={(e) => setConfirmed(e.target.checked)} /> I understand this is my one and only correction and the details will be locked permanently.</label><div className="mt-5 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button type="button" onClick={() => { setConfirmOpen(false); setConfirmed(false); }} className="min-h-12 rounded-xl border border-white/10 px-5 font-medium">Go Back</button><button type="button" disabled={!confirmed} onClick={() => void save()} className="min-h-12 rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 px-5 font-semibold disabled:opacity-40">Save and Lock Forever</button></div></div></div>}
  </div>;
}
function Notice({ title, children }: { title: string; children: React.ReactNode }) { return <div className="rounded-2xl border border-sky-300/15 bg-sky-400/[.06] p-4"><div className="flex items-start gap-3"><span aria-hidden="true" className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-sky-400/10 text-sky-200">🔒</span><div><h3 className="font-medium text-sky-100">{title}</h3><p className="mt-1 text-sm leading-6 text-white/50">{children}</p></div></div></div>; }
function Field({ label, value, onChange, type = "text", ...props }: { label: string; value: string; onChange: (value: string) => void; type?: string } & Omit<React.InputHTMLAttributes<HTMLInputElement>, "value" | "onChange" | "type">) { return <label className="block text-sm text-white/65">{label}<input {...props} type={type} value={value} onChange={(e) => onChange(e.target.value)} className="mt-2 min-h-12 w-full rounded-xl border border-white/10 bg-[#020817]/70 px-3 text-base text-white outline-none focus:border-sky-400/50 disabled:opacity-40" /></label>; }
function Rows({ details }: { details: BirthDetails }) { return <div className="grid gap-3 sm:grid-cols-2"><Row label="Full name used for calculations" value={details.fullName || "Not available"} wide /><Row label="Date of birth" value={details.dateOfBirth} /><Row label="Birth time" value={details.birthTimeKnown ? details.birthTime : "Unknown"} /><Row label="Birth time accuracy" value={details.birthTimeKnown ? "Exact birth time provided" : "Exact birth time is unknown"} /><Row label="Birth place" value={details.birthPlace || "Not available"} wide /></div>; }
function Row({ label, value, wide = false }: { label: string; value: string; wide?: boolean }) { return <div className={`min-w-0 rounded-2xl border border-white/[.08] bg-white/[.025] p-4 ${wide ? "sm:col-span-2" : ""}`}><p className="text-xs font-medium uppercase tracking-[.12em] text-white/35">{label}</p><p className="mt-2 break-words text-[15px] leading-6 text-white/80">{value}</p></div>; }
